### ISSUE TITLE
Cannot reference images from sass

### ISSUE THREAD

**Issue by DanielHeath** [koluch/esbuild-plugin-sass#1]
Let me start by saying: This is really cool! It gets me 99% of the way to being able to use esbuild for my old, crufty app.

Sass has url helpers that hook into your asset build process. 

However, you need to configure lookup paths etc. 

If `sassRender` was the default value for a `sassRender` option, I could override it to set those.

However, that's not quite enough, because you also need to emit the paths to the images used so that esbuild knows to copy them into the output directory. I'm not familiar with that API, and the way it's currently used in this repo doesn't have an obvious hook to add more files.

**Comment by koluch** [comment]
Hi @DanielHeath! Thanks a lot for feedback!

That's a good point, I will try to find a good way to fix it. It looks like I just need to rewrite all `url(...)` in generated CSS file
