### ISSUE TITLE
error: [sass] Can't find stylesheet to import

### ISSUE THREAD

**Issue by rodoabad** [koluch/esbuild-plugin-sass#13]
I'm having some trouble with files that use `@import`. Unsure how to proceed on this one.

```
│ @import '~@foo/branding/styles/variables';
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
| src/card/card.module.scss 1:9  root stylesheet
│ import styles from './card.module.scss';
│                    ~~~~~~~~~~~~~~~~~~~~
│ node_modules/esbuild-plugin-sass/index.js:92:14: note: This error came from the "onResolve" callback registered here
│         build.onResolve({ filter: /.\.(scss|sass)$/, namespace: "file" }, async (args) => {
╵               ~~~~~~~~~
```

**Comment by koluch** [comment]
Hi @rodoabad,

Are you trying to import stylesheet from `node_modules/@foo/branding/...`, using webpack feature to resolve `~` to `node_modules`? `esbuild` doesn't support this feature. 

You can import stylesheet you need, specifying relative path explicitly, like this:
```sass
@import './node_modules/@foo/branding/styles/variables'
```

**Comment by rodoabad** [comment]
Thanks. Looks like I have to change all references to that pattern.
