### ISSUE TITLE
SCSS files not watched.

### ISSUE THREAD

**Issue by JamesBurgoon** [koluch/esbuild-plugin-sass#14]
It appears changes to SCSS files are not watched.

Example:

```
const esbuild = require('esbuild');
const sassPlugin = require('esbuild-plugin-sass');

esbuild.build({
  entryPoints: ['src/index.js'],
  bundle: true,
  outfile: 'bundle.js',
  plugins: [sassPlugin()],
  watch: {
    onRebuild(error, result) {
      if (error) console.error('watch build failed:', error)
      else console.error('watch build succeeded:', result)
    },
  },
}).catch((e) => console.error(e.message));
```
Changes to `src/index.js` are watched, but changes to `src/test.scss` are not.

**Comment by koluch** [comment]
Hi @JamesBurgoon,

I managed to fix this issue, it should work properly now. Sorry for long response!

**Comment by JamesBurgoon** [comment]
Cool!
Unfortunately any imported .scss files are not watched. Example, if `src/test.scss` imports another .scss file (`src/_another.scss`), the imported file is not watched.
```
@import 'another';
```
`src/test.scss` is watched perfectly however.

**Comment by JamesBurgoon** [comment]
> Unfortunately any imported .scss files are not watched. Example, if `src/test.scss` imports another .scss file (`src/_another.scss`), the imported file is not watched.

You could derive the scss folder from the first scss file and then use Glob to grab all scss file into an array watch. For example, this works:

```
            const sourceFullPath = path.resolve(args.resolveDir, args.path);
            const scssPath = `${path.dirname(sourceFullPath)}/`;
            const scssFilePaths = await glob.sync(`${scssPath}**/*.scss`);
            ...
            return {
                path: tmpFilePath,
                watchFiles: scssFilePaths,
            };

```

**Comment by DarioDaF** [comment]
I think this issue should be reopened because imported scss should be watched by this library, or am I missing some decision to leave it as is for reasons?
