### ISSUE TITLE
Mark URLs as external

### ISSUE THREAD

**Issue by johnstew** [koluch/esbuild-plugin-sass#20]
Running into an issue where all URLs within my files are being replaced when I'd like them to be marked as externals. The plugin is trying to construct a path but ends up creating a bad path because the URL is actually an external reference. This causes esbuild to look for that path and then it errors out cuz it can't find it. 

Example URL in SASS file: `background-image: url(/static/assets/images/img-arrows.svg);`
Path created: `background-image: url("../../../../../../../../../../../Users/john/dev/myproject/static/assets/images/img-arrows.svg");`

**Comment by koluch** [comment]
Hi @johnstew,

Thanks a lot for you contrubution! I decided to change your code a little: esbuild already supports `external` option, I just use it instead of special plugin option. I will include this fix in next release

**Comment by johnstew** [comment]
@koluch That makes sense, I should of gone that route instead. Thanks for fixing this!
