### ISSUE TITLE
Just processing .scss files

### ISSUE THREAD

**Issue by bl-ue** [koluch/esbuild-plugin-sass#4]
What about directly building `.scss`, without having to build a `.js` file that imports the `.scss` file?

**Comment by DanielHeath** [comment]
It seems like you could do that more easily by using sass directly - I'm not clear on what benefit esbuild brings if you're not going to use the scss files from javascript.

**Comment by bl-ue** [comment]
Well, esbuild is really fast, I'd like to use one build tool, etc.  But I also may not get the point yet.  I'm pretty new to esbuild.

**Comment by koluch** [comment]
Sorry, this issue doesn't seem to be relevant to this plugin

**Comment by bl-ue** [comment]
No problem, @koluch.  I was just hoping that if I threw a few words at you, you'd get my point and be able to help me 😄
