### ISSUE TITLE
`No overload matches this call` with esbuild v0.14.24

### ISSUE THREAD

**Issue by nandenjin** [koluch/esbuild-plugin-sass#56]
esbuild v0.14.24 contains a change on `sourcemap` in the build options, and that makes type checks failed.

https://github.com/evanw/esbuild/commit/b6f826efbde6c5461eb1e8703dd1fbe8f6bf7e2f

```ts
import { build } from 'esbuild'
import { sassPlugin } from 'esbuild-sass-plugin'

build({
  entryPoints: [
    './index.ts',
  ],
  bundle: true,
  target: ['es2019'],
  outdir: './dist',
  plugins: [sassPlugin()],
})
```

```
// By executing tsc --noEmit:
Types of property 'sourcemap' are incompatible.
  Type 'boolean | "linked" | "inline" | "external" | "both" | undefined' is not assignable to type 'boolean | "inline" | "external" | "both" | undefined'.
  Type '"linked"' is not assignable to type 'boolean | "inline" | "external" | "both" | 
```

<details>
<summary>Full stacktrace</summary>
<output>
<pre>
<code>
Error: build.ts(2[9](https://github.com/my-project/runs/5432456560?check_suite_focus=true#step:7:9),[13](https://github.com/my-project/runs/5432456560?check_suite_focus=true#step:7:13)): error TS[27](https://github.com/my-project/runs/5432456560?check_suite_focus=true#step:7:27)69: No overload matches this call.
  The last overload gave the following error.
    Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin'.
      Types of property 'setup' are incompatible.
        Type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>' is not assignable to type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>'.
          Types of parameters 'build' and 'build' are incompatible.
            Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild'.
              The types of 'initialOptions.plugins' are incompatible between these types.
                Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin[] | undefined' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin[] | undefined'.
                  Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin[]' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin[]'.
                    Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin'.
                      Types of property 'setup' are incompatible.
                        Type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>' is not assignable to type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>'.
                          Types of parameters 'build' and 'build' are incompatible.
                            Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild'.
                              The types of 'esbuild.build' are incompatible between these types.
                                Type '{ (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").BuildOptions & { write: false; }): Promise<...>; (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main")....' is not assignable to type '{ (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildOptions & { write: false; }): Promise<import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildResult & { ...; }>; (options: import("/home/runner/work/my-project/theme...'.
                                  Types of parameters 'options' and 'options' are incompatible.
                                    Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildOptions & { write: false; }' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").BuildOptions & { write: false; }'.
                                      Type 'BuildOptions & { write: false; }' is not assignable to type 'BuildOptions'.
                                        Types of property 'plugins' are incompatible.
                                          Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin[] | undefined' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin[] | undefined'.
                                            Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin[]' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin[]'.
                                              Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").Plugin'.
                                                Types of property 'setup' are incompatible.
                                                  Type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>' is not assignable to type '(build: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>'.
                                                    Types of parameters 'build' and 'build' are incompatible.
                                                      Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").PluginBuild' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").PluginBuild'.
                                                        The types of 'esbuild.build' are incompatible between these types.
                                                          Type '{ (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").BuildOptions & { write: false; }): Promise<...>; (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main")....' is not assignable to type '{ (options: import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildOptions & { write: false; }): Promise<import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildResult & { ...; }>; (options: import("/home/runner/work/my-project/theme...'.
                                                            Types of parameters 'options' and 'options' are incompatible.
                                                              Type 'BuildOptions' is not assignable to type 'BuildOptions & { write: false; }'.
                                                                Type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild/lib/main").BuildOptions' is not assignable to type 'import("/home/runner/work/my-project/my-project/node_modules/esbuild-sass-plugin/node_modules/esbuild/lib/main").BuildOptions'.
                                                                  Types of property 'sourcemap' are incompatible.
                                                                    Type 'boolean | "linked" | "inline" | "external" | "both" | undefined' is not assignable to type 'boolean | "inline" | "external" | "both" | undefined'.
                                                                      Type '"linked"' is not assignable to type 'boolean | "inline" | "external" | "both" | undefined'.
</code>
</pre>
</output>
</details>

**Comment by koluch** [comment]
Hi @nandenjin,

It seems you are using different plugin, [esbuild-sass-plugin](https://github.com/glromeo/esbuild-sass-plugin), and this is a repo of a `esbuild-plugin-sass` plugin :)
