### ISSUE TITLE
Import from node_modules

### ISSUE THREAD

**Issue by JonnyVaine** [koluch/esbuild-plugin-sass#59]
I'm trying to convert my current webpack project to ESBuild, and my scss files import a stylesheet from a node module like this:

`@import '~breakpoint-sass/stylesheets/breakpoint';`

However, I get the following error message:

X [ERROR] [plugin sass] Can't find stylesheet to import.
  ╷
1 │ @import '~breakpoint-sass/stylesheets/breakpoint.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\Frontend\src\modules\Carousel\Carousel.scss 1:9  root stylesheet

    src/Frontend/src/modules/Carousel/Carousel.js:7:7:
      7 │ import './Carousel.scss';
        ╵        ~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild-plugin-sass/index.js:100:14:
      100 │         build.onResolve({ filter: /.\.(scss|sass)$/, namespace: "file" }, async (args) => {
          ╵               ~~~~~~~~~

Do I need to setup an alias, or is there a way to enable this within the plugin?

**Comment by stephenjwatkins** [comment]
I was running into a similar issue for a component library in a yarn monorepo. I removed the `~` tilde prefix and adjusted my `loadPaths` in the SASS options to fix it.

```
sassPlugin({
  customSassOptions: {
    loadPaths: [path.join(__dirname, "../../node_modules")],
  },
})
```
