### ISSUE TITLE
[FEATURE] load path option

### ISSUE THREAD

**Issue by danny007in** [koluch/esbuild-plugin-sass#7]
like https://sass-lang.com/documentation/cli/dart-sass#load-path

**Comment by unlocomqx** [comment]
I think it's better to just pass all the options from the plugin to sass or add a sassOptions section for this.
I usually need to pass includePaths to load my files correctly

**Comment by flipsasser** [comment]
Added a PR to support that, @unlocomqx: https://github.com/koluch/esbuild-plugin-sass/pull/29

**Comment by koluch** [comment]
Hi @unlocomqx,

Thanks for you code! I made a little change in your code, now to pass sass-options there is a special options field `customSassOptions`, I think it would be clearer to use. It's already released in v0.6.0
