### ISSUE TITLE
Typescript support :/

### ISSUE THREAD

**Issue by creepinson** [koluch/esbuild-plugin-sass#9]
Can we have typescript support added, as in https://github.com/igoradamenko/esbuild-plugin-alias/issues/1

I want to run the esbuild programatically in typescript, but this won't work unless I write it in vanilla node.js :/

**Comment by creepinson** [comment]
I could also make a pr for this if needed - just really annoying to see that esbuild supports ts but not any of the plugins.

**Comment by koluch** [comment]
Hi @creepinson,

Your are right, this package should be packed with TS definitions. I think, I will rewrite it on TS, since it is a small package, in next few days
